import argparse
import math

from pythonosc import dispatcher
from pythonosc import osc_server

def print_volume_handler(unused_addr, args, volume):
  print("[{0}] ~ {1}".format(args[0], volume))

def print_compute_handler(unused_addr, args, volume):
  try:
    print("[{0}] ~ {1}".format(args[0], args[1](volume)))
  except ValueError: pass

def parseFFT(addr, *args):
    # args is a tuple of 126 values
    # First value is channel #
    # Next 125 values are the amplitude values of the ith frequency

    # print(len(args))
    pass

def parseTimeSeries(addr, *args):
    print("TS: ",args)

def parseBandPower(addr, *args):
    print("BP: ",args)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--ip",
        default="127.0.0.1", help="The ip to listen on")
    parser.add_argument("--port",
        type=int, default=12345, help="The port to listen on")
    args = parser.parse_args()

    dispatcher = dispatcher.Dispatcher()
    dispatcher.map("/openbciFFT", parseFFT)
    dispatcher.map("/openbciTS", parseTimeSeries)
    dispatcher.map("/openbciBP", parseBandPower)

    server = osc_server.ThreadingOSCUDPServer(
        (args.ip, args.port), dispatcher)
    print("Serving on {}".format(server.server_address))
    server.serve_forever()
    while (True):
        inp = input()
        if inp == "calibrate":
            # Run calibration
            # Use data generated by parseBandPower over 1 minute
            #   Running average or time-weighted average
            # Change to next state combination by sending a request to 
            #   http://localhost:3000/i
            # where i is the index of the state combination
            # REST in Python: http://docs.python-requests.org/en/latest/
            #
            # Store most focused state combination and most relaxed state combination
            pass
        if inp == "relax":
            # Use the calibrated settings to make user relaxed
            pass
        if inp == "focus":
            # Use the calibrated settings to make user focused
            pass